version: "3"
services:
  node:
    image: node:9.6.0
    ports:
      - "3000:3000"
    volumes:
      - ./node/:/node/
    working_dir: /node
    command: npm start
    links:
     - mongo
    networks:
     web_net:
       ipv4_address: 192.168.99.11
      
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/:/data/db
      
